### ISSUE TITLE
spec.loadBalancerIP field of Service resource with type: LoadBalancer gets discarded

### ISSUE THREAD

**Issue by invidian** [gardener/gardener-resource-manager#107]
**How to categorize this issue?**

/area networking
/kind bug
/priority normal

**What happened**:

In https://github.com/gardener/gardener-extension-provider-packet, CCM sets `spec.loadBalancerIP` field for `Services` of `type: LoadBalancer` with the Elastic IP assigned to each service. This IP is then picked up by MetalLB and announced by `Service`.

However, for services managed by `Gardener-Resource-Manager` like `kube-system/vpn-shoot`, the `spec.loadBalancerIP` gets emptied every minute, when `Gardener-Resource-Manager` runs it's reconciliation loop. This breaks the Shoot VPN, making Shoot cluster state unstable.

**What you expected to happen**:

When `spec.loadBalancerIP` field is set on target resource and it is not specified on source resource, Gardener-Resource-Manager should merge both values instead of removing it from target resource.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a `Service` object managed by Resource managed without `spec.loadBalancerIP` set.
2. Set `spec.loadBalancerIP` using API on target cluster.
3. Wait up to a minute for Gardener-Resource-Manager to remove the value of this field.

**Anything else we need to know?**:

Perhaps https://github.com/gardener/gardener-resource-manager/blob/master/pkg/controller/managedresource/merger.go#L227 could be changed to preserve this field.

CC @timebertt @deitch 

**Environment**:

- Gardener-Resource-Manager version:
- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration: Packet/EM
- Others:

**Comment by deitch** [comment]
Seconding this. The `spec.loadBalancerIP` is there for the user to specify a desired load balancer IP from the load balancer provider. While GRM may have no interest in setting this, an intermediate stage very well may. 

In the case of Equinix Metal (EM), unlike hyperscalers with ELBs such as AWS or Azure, the provision of a load balancer and the provision of an IP are 2 distinct phases.

EM CCM "bridges the gap" by seeing the request for service `type=loadBalancer`, getting the EIP, and setting it in `spec.loadBalancerIP`. This enables downstream loadbalancers, such as metallb or kube-vip, to create the loadbalancer.

For example, metallb consumes the request for a specific IP using that annotation, docs [here](https://metallb.universe.tf/usage/#requesting-specific-ips); kube-vip does the same, docs [here](https://kube-vip.io/hybrid/services/#flow).

I definitely am open to other ways of doing this, if such exist, as long as they remain within the specs.

**Comment by rfranzke** [comment]
I think this is totally valid behaviour but a special case that is not yet handled by GRM (not on purpose but simply because the use-case didn't exist). It's similar to preserving the `.spec.ports[].nodePort` in `Service`s if I understand it correctly. 
https://github.com/gardener/gardener-resource-manager/blob/b69b35288b74d1dea448d04a7150f9314e0c82aa/pkg/controller/managedresource/merger.go#L227-L285 would be the function that needs to be adapted.

**Comment by deitch** [comment]
Pretty much @rfranzke . So it looks like you already have exception code for `.spec.ports[].nodePort` in lines 250-260. Is this just a question of also adding an exception there that checks if `spec.LoadBalancerIP` is already set on the retrieved one but not on the reference, and if so, leave it alone?

In the above code, is `newService` what it is being reconcile to, and `oldService` what was retrieved from the cluster?

**Comment by rfranzke** [comment]
>  Is this just a question of also adding an exception there that checks if spec.LoadBalancerIP is already set on the retrieved one but not on the reference, and if so, leave it alone?

IIUIC, yes.

> In the above code, is newService what it is being reconcile to, and oldService what was retrieved from the cluster?

Yes, right.

**Comment by deitch** [comment]
That sounds simple enough.

**Comment by invidian** [comment]
I will open a PR then.

In the meanwhile, is there some workaround we could do to preserve `spec.loadBalancerIP` for now? Maybe deploying a job as part of Shoot controlplane which would annotate `kube-system/vpn-shoot` service with `resources.gardener.cloud/ignore: "true"` ?

**Comment by deitch** [comment]
Sort of like this? https://github.com/gardener/gardener-resource-manager/pull/108

If I knew how your testing system worked, I would add the tests to `merger_test.go`

**Comment by invidian** [comment]
>If I knew how your testing system worked, I would add the tests to merger_test.go

You should start with tests :)

**Comment by deitch** [comment]
Uh uh. _Sometimes_ start with tests, when you know what you are after. If you need some basic code to get agreement on what "it" is, it is ok to start without. It isn't good to be an ideologue. :-)

**Comment by rfranzke** [comment]
> Maybe deploying a job as part of Shoot controlplane which would annotate kube-system/vpn-shoot service with resources.gardener.cloud/ignore: "true" ?

I think this effort is not necessary now that #108 is already open and approved. Once merged, I guess we can draft a new GRM release (there are also other changes that we would like to release), cc @timebertt @timuthy

**Comment by timebertt** [comment]
New release sgtm
