### ISSUE TITLE
Finalizer is not removed from secret

### ISSUE THREAD

**Issue by tim-ebert** [gardener/gardener-resource-manager#52]
**What happened**:
If you remove a `secretRef` from a MR, grm will not remove its finalizer from the referenced Secret.
Therefore the secret cannot be deleted without manual intervention.

With https://github.com/gardener/gardener/pull/2210 (which creates dedicated secrets for each worker pool and references each of them in the respective MR) this will lead to a problem when g/grm is released, that the Shoot's namespace in the Seed cannot be deleted anymore, if the enduser has removed a worker pool from their Shoot (because it will contain Secrets with stale finalizers).

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot with 2 worker pools
2. Remove one worker pool
3. Delete the Shoot
4. Observe that the Shoot's namespace in the Seed can't be deleted (pending deletion of secret for the second worker pool's cloud config)

**Anything else we need to know**:

**Environment**:

**Comment by rfranzke** [comment]
As discussed via phone, this could be done similar to gardener/gardener#1993 with a separate reconciler for `Secret`s whose sole job it is to add/remove the finalizer. https://github.com/gardener/gardener/blob/master/pkg/controllermanager/controller/controllerregistration/controllerregistration_control.go#L101-L127 is a similar separate reconciler for `ControllerRegistration`s that adds/removes finalizers if it is (not) referenced by `ControllerInstallation`s.
