### ISSUE TITLE
`status` of `VerticalPodAutoscaler` objects is not kept

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-resource-manager#58]
**How to categorize this issue?**

/area usability
/kind bug
/priority normal

**What happened**:
The `status` is not kept when the GRM reconciles a `VerticalPodAutoscaler` object because the `VerticalPodAutoscaler` CRD does not support subresources.
Most likely all other CRDs without support for `status` subresource are affected as well.

**What you expected to happen**:
The GRM should not overwrite the `status`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a `VerticalPodAutoscaler`
1. See `status` being overwritten.

**Anything else we need to know?**:
-

**Environment**:

- Gardener-Resource-Manager version: v0.12.0
- Cloud provider or hardware configuration: all

**Comment by tim-ebert** [comment]
Have you tried the current master?
I think I have fixed this with https://github.com/gardener/gardener-resource-manager/pull/44 but it’s not yet released.

**Comment by rfranzke** [comment]
You're right, thanks, this PR should already fix it. We should work on a new release to get the many improvements out.
/close

**Comment by tim-ebert** [comment]
Yes, indeed. Sorry for delaying.
I think, the current master should be good to go for a release. Let's get it out this week.
