### ISSUE TITLE
Shoot stuck in deletion due to stuck `ManagedResource`

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-resource-manager#78]
**How to categorize this issue?**

/area usability
/kind bug
/priority normal

**What happened**:
Shoot was stuck in deletion with the following error:

  ```text
  Waiting until extension resources have been deleted" failed: 1 error occurred:
  * Failed to delete Extension shoot--foo--bar/shoot-dns-service: Error deleting Extension resource: timed out waiting for the condition
  ```

  Checking the logs of the gardener-resource-manager revealed:

  ```text
  {"level":"info","ts":"2020-10-21T13:09:03.264Z","logger":"gardener-resource-manager.reconciler","msg":"reconcile: action required: true, responsible: true","object":"shoot--foo--bar/extension-shoot-dns-service-seed"}
  {"level":"info","ts":"2020-10-21T13:09:03.264Z","logger":"gardener-resource-manager.reconciler","msg":"Starting to delete ManagedResource","object":"shoot--foo--bar/extension-shoot-dns-service-seed"}
  {"level":"info","ts":"2020-10-21T13:09:03.843Z","logger":"gardener-resource-manager.reconciler","msg":"All resources have been deleted, removing finalizers from ManagedResource","object":"shoot--foo--bar/extension-shoot-dns-service-seed"}
  {"level":"error","ts":"2020-10-21T13:09:07.325Z","logger":"controller-runtime.controller","msg":"Reconciler error","controller":"resource-controller","request":"shoot--foo--bar/extension-shoot-dns-service-seed","error":"error removing finalizer from ManagedResource: Operation cannot be fulfilled on managedresources.resources.gardener.cloud \"extension-shoot-dns-service-seed\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/gardener/gardener-resource-manager/vendor/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/github.com/gardener/gardener-resource-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/gardener/gardener-resource-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/src/github.com/gardener/gardener-resource-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/gardener/gardener-resource-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/gardener/gardener-resource-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/gardener/gardener-resource-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
  ```

After that, the GRM never tried to remove the finalizer again, leading to the stuck `ManagedResource` in the system.

**What you expected to happen**:
GRM retries to remove its finalizer

**How to reproduce it (as minimally and precisely as possible)**:
n/a yet, sorry

**Environment**:

- Gardener-Resource-Manager version: v0.17.0
- Kubernetes version (use `kubectl version`): v1.17.8

**Comment by timebertt** [comment]
Hmm, not sure if this solves the issue, but we should switch to patching finalizers and using the c-r helper funcs like here:
https://github.com/gardener/gardener/blob/9af2e8a04a08cb78c66bbdc0ab47af577c5b28d2/pkg/controllerutils/finalizers.go#L35-L55

Still, I'm not sure, why grm didn't retry the reconciliation...

**Comment by rfranzke** [comment]
Yeah, using PATCH makes sense.

> Still, I'm not sure, why grm didn't retry the reconciliation...

Same here, I still need to try to reproduce it. As said yesterday, it might also be the case that it "just" was in an exponential backoff and would have retried if I would have waited longer.

**Comment by ialidzhikov** [comment]
I also had a short look and currently I don't see any obvious reason. For @timebertt 's suggestion in https://github.com/gardener/gardener-resource-manager/issues/78#issuecomment-714932828 -> https://github.com/gardener/gardener-resource-manager/pull/87.

**Comment by rfranzke** [comment]
OK, thanks @ialidzhikov, then let's
/close
this issue for now as there are no clear steps for reproduction anyways and as I wasn't sure whether it's just exponential backoff.
#87 is merged and will definitely help.
In case we see this problem again we can reopen the issue, of course.
