### ISSUE TITLE
Add option to disable target cache

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener-resource-manager#92]
**How to categorize this issue?**

/area quality robustness cost
/kind bug
/priority normal

**What happened**:

We observed a Shoot cluster which had a lot of very large secrets (~3000 with ~1MiB each).
As the gardener-resource-manager caches all objects in the target cluster it touches, its cache had grown to an inacceptable size:
```
$ k top po
NAME                                          CPU(cores)   MEMORY(bytes)
gardener-resource-manager-77876b69b7-kvvkz    400m         5875Mi
```

Also, one of its worker routines trying to get a secret for applying was stuck, as the client tried to aquire a watch, but the API server panic'd (for some reasons), so the client waited forever for the watch cache to sync:
```
I1127 13:55:38.982551       1 trace.go:201] Trace[4834220]: "Reflector ListAndWatch" name:sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224 (27-Nov-2020 13:54:00.969) (total time: 60013ms):
Trace[4834220]: [1m0.013079589s] [1m0.013079589s] END
E1127 13:55:38.982571       1 reflector.go:178] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to list *v1.Secret: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 57251; INTERNAL_ERROR
```

**What you expected to happen**:

grm should be resistent to such user behaviour and should therefore allow to disable the target cache via a command line flag.
This way, gardener can deploy grm instances for Shoots without a cache for the Shoot API server to avoid failing watches and minimize the memory footprint.

/cc @mandelsoft @timuthy 

**Environment**:

- Gardener-Resource-Manager version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
When would gardener disable the target cache, i.e., when would it set this CLI flag? Always? It could, because communication GRM -> KAPI is anyways cluster-internally, so network I/O is not a problem.

**Comment by timebertt** [comment]
Yes, I was thinking about setting it always, as grm is anyways sitting right next to the API server.
